version: '3.3'

services:
  mysql-slowlog-analyzer:
    build: .
    container_name: mysql_slowlog_analyzer
    restart: unless-stopped
    
    # 环境变量
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      # MySQL慢日志配置
      - SLOWLOG_PATH=${SLOWLOG_PATH:-/app/slowlogs/*.log}
      - TOP_DAILY=${TOP_DAILY:-30}
      - TOP_WEEKLY=${TOP_WEEKLY:-50}
      - TOP_MONTHLY=${TOP_MONTHLY:-100}
      - MIN_TIME=${MIN_TIME:-1.0}
      - JOBS=${JOBS:-4}
      - EXCLUDE_DUMPS=${EXCLUDE_DUMPS:-true}
      # Elasticsearch配置
      - ES_HOST=${ES_HOST}
      - ES_USER=${ES_USER}
      - ES_PASSWORD=${ES_PASSWORD}
      - HOSTNAME=${ANALYZER_HOSTNAME:-mysql-slowlog-analyzer}
    
    # 目录挂载
    volumes:
      # 慢日志文件目录（支持绝对路径，只读）
      - ${SLOWLOG_HOST_PATH:-./slowlogs}:/app/slowlogs:ro
      # 分析结果输出目录
      - ./output:/app/output
      # 运行日志目录
      - ./logs:/app/logs
    
    # 资源限制
    mem_limit: 2g
    cpus: 2.0
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
